# Import the relevant libraries

In [1]:
import numpy as np

# Declaring scalars, vectors and matrices

## Scalars

In [3]:
a = 5

In [4]:
a

5

## Vector

In [7]:
v = np.array([5,-2,4])
v

array([ 5, -2,  4])

## Matrices

In [9]:
m = np.array([[5, 12, 6], [-3, 0, 14]])
m

array([[ 5, 12,  6],
       [-3,  0, 14]])

## Data types

In [10]:
type(a)

int

In [11]:
type(v)

numpy.ndarray

In [12]:
type(m)

numpy.ndarray

In [13]:
s_array = np.array(5)
s_array

array(5)

In [14]:
type(s_array)

numpy.ndarray

## Data Shapes

In [15]:
m.shape

(2, 3)

In [16]:
v.shape

(3,)

### Creating a column vector

In [17]:
v.reshape(1,3)

array([[ 5, -2,  4]])

In [18]:
v.reshape(3,1)

array([[ 5],
       [-2],
       [ 4]])

- #### Skalers does not have a shape

In [19]:
a.shape

AttributeError: 'int' object has no attribute 'shape'

In [20]:
s_array.shape

()