# Import the relevant libraries

In [29]:
import numpy as np

## Addition

In [30]:
m1 = np.array([[5,12,6],[-3,0,14]])
m1

array([[ 5, 12,  6],
       [-3,  0, 14]])

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [31]:
m2 = np.array([[9,8,7],[1,3,-5]])
m2

array([[ 9,  8,  7],
       [ 1,  3, -5]])

array([[ 9,  8,  7],
       [ 1,  3, -5]])

In [32]:
m1 + m2

array([[14, 20, 13],
       [-2,  3,  9]])

array([[14, 20, 13],
       [-2,  3,  9]])

## Difference

### Example 1

In [33]:
m3 = np.array([[5,3],[-2,4]])
m4 = np.array([[7,-5],[3,8]])

In [34]:
m3

array([[ 5,  3],
       [-2,  4]])

array([[ 5,  3],
       [-2,  4]])

In [35]:
m4

array([[ 7, -5],
       [ 3,  8]])

array([[ 7, -5],
       [ 3,  8]])

In [36]:
m3 - m4

array([[-2,  8],
       [-5, -4]])

array([[-2,  8],
       [-5, -4]])

### Example 2

In [37]:
m5 = np.array([[22.33,-4.73],[-203.14,1200.02],[4.22,234.1]])
m5

array([[  22.33,   -4.73],
       [-203.14, 1200.02],
       [   4.22,  234.1 ]])

array([[  22.33,   -4.73],
       [-203.14, 1200.02],
       [   4.22,  234.1 ]])

In [38]:
m6 = np.array([[131.13,448.29],[-340.21,1.06],[30.41,424.99]])
m6

array([[ 131.13,  448.29],
       [-340.21,    1.06],
       [  30.41,  424.99]])

array([[ 131.13,  448.29],
       [-340.21,    1.06],
       [  30.41,  424.99]])

In [39]:
m5 - m6

array([[-108.8 , -453.02],
       [ 137.07, 1198.96],
       [ -26.19, -190.89]])

array([[-108.8 , -453.02],
       [ 137.07, 1198.96],
       [ -26.19, -190.89]])

## Adding vectors together

In [40]:
v1 = np.array([1,2,3,4,5])
v2 = np.array([5,4,3,2,1])

In [41]:
v1 + v2

array([6, 6, 6, 6, 6])

array([6, 6, 6, 6, 6])

In [42]:
v1 - v2

array([-4, -2,  0,  2,  4])

array([-4, -2,  0,  2,  4])